// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCt-zZ01JRgIcIkUdmUHInRKsJKe9iuBA',
    appId: '1:387858945348:android:dafd5bc44c53233e743311',
    messagingSenderId: '387858945348',
    projectId: 'ccmap-26dca',
    storageBucket: 'ccmap-26dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqzMOOcxWaCJwPy2deWOp1TFE_HFxUHI',
    appId: '1:387858945348:ios:b108230ad22465c4743311',
    messagingSenderId: '387858945348',
    projectId: 'ccmap-26dca',
    storageBucket: 'ccmap-26dca.firebasestorage.app',
    iosClientId: '387858945348-h347dbt6ngea9mcfpe8flputrv47bl7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdI5sJIqDxiQq0Z1W7cyL97s4sXfKBbPA',
    appId: '1:387858945348:web:a305ecff5eb6ac62743311',
    messagingSenderId: '387858945348',
    projectId: 'ccmap-26dca',
    authDomain: 'ccmap-26dca.firebaseapp.com',
    storageBucket: 'ccmap-26dca.firebasestorage.app',
    measurementId: 'G-113Q8FT6DE',
  );
}
